import * as XLSX from 'xlsx';

interface TestCase {
  feature: string;
  testCaseId: string;
  testCaseDescription: string;
  preconditions: string;
  testSteps: string;
  expectedResult: string;
  priority: 'High' | 'Medium' | 'Low';
  status: 'Not Tested' | 'Pass' | 'Fail' | 'Blocked';
  notes: string;
  tester: string;
  dateTested: string;
  environment: 'Dev' | 'Staging' | 'Production';
}

const testCases: TestCase[] = [
  // ========== AUTHENTICATION & AUTHORIZATION ==========
  {
    feature: 'User Registration',
    testCaseId: 'AUTH-001',
    testCaseDescription: 'User can register with valid email and password',
    preconditions: 'User is on signup page, email not already registered',
    testSteps: '1. Navigate to /auth/signup\n2. Enter valid email\n3. Enter password (min 8 chars)\n4. Click Register',
    expectedResult: 'Account created, verification email sent, user redirected to verification page',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'User Registration',
    testCaseId: 'AUTH-002',
    testCaseDescription: 'Registration fails with duplicate email',
    preconditions: 'Email already exists in database',
    testSteps: '1. Navigate to /auth/signup\n2. Enter existing email\n3. Enter password\n4. Click Register',
    expectedResult: 'Error message: "Email already registered"',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'User Registration',
    testCaseId: 'AUTH-003',
    testCaseDescription: 'Registration fails with invalid email format',
    preconditions: 'User is on signup page',
    testSteps: '1. Enter invalid email (e.g., "invalid-email")\n2. Enter password\n3. Click Register',
    expectedResult: 'Validation error: "Invalid email format"',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'User Registration',
    testCaseId: 'AUTH-004',
    testCaseDescription: 'Registration fails with weak password',
    preconditions: 'User is on signup page',
    testSteps: '1. Enter valid email\n2. Enter password < 8 characters\n3. Click Register',
    expectedResult: 'Validation error: "Password must be at least 8 characters"',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'User Registration',
    testCaseId: 'AUTH-005',
    testCaseDescription: 'Rate limiting on registration endpoint',
    preconditions: 'User attempts multiple registrations',
    testSteps: '1. Attempt 6 registrations within 1 hour from same IP\n2. Observe response',
    expectedResult: '5th attempt succeeds, 6th attempt returns 429 Too Many Requests',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Verification',
    testCaseId: 'AUTH-006',
    testCaseDescription: 'User can verify email with valid token',
    preconditions: 'User registered, verification email received',
    testSteps: '1. Click verification link in email\n2. Token is valid and not expired',
    expectedResult: 'Email verified, status changed to "active", welcome email sent, user can sign in',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Verification',
    testCaseId: 'AUTH-007',
    testCaseDescription: 'Email verification fails with expired token',
    preconditions: 'Verification token expired (>24 hours old)',
    testSteps: '1. Click expired verification link\n2. Observe response',
    expectedResult: 'Error: "Verification token expired. Please request a new one."',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Verification',
    testCaseId: 'AUTH-008',
    testCaseDescription: 'Email verification fails with invalid token',
    preconditions: 'Invalid or tampered token',
    testSteps: '1. Navigate to /auth/verify-email with invalid token\n2. Submit',
    expectedResult: 'Error: "Invalid verification token"',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Verification',
    testCaseId: 'AUTH-009',
    testCaseDescription: 'User can resend verification email',
    preconditions: 'User registered but email not verified',
    testSteps: '1. Navigate to /auth/resend-verification\n2. Enter email\n3. Click Resend',
    expectedResult: 'New verification email sent, rate limit applied (max 3 per hour)',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-010',
    testCaseDescription: 'User can sign in with valid credentials',
    preconditions: 'User registered and email verified',
    testSteps: '1. Navigate to /auth/signin\n2. Enter verified email\n3. Enter correct password\n4. Click Sign In',
    expectedResult: 'User signed in, session created, redirected based on role (admin→/admin, student→/dashboard)',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-011',
    testCaseDescription: 'Sign in fails with unverified email',
    preconditions: 'User registered but email not verified',
    testSteps: '1. Navigate to /auth/signin\n2. Enter unverified email\n3. Enter password\n4. Click Sign In',
    expectedResult: 'Error: "Please verify your email before signing in" with resend option',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-012',
    testCaseDescription: 'Sign in fails with incorrect password',
    preconditions: 'User exists with verified email',
    testSteps: '1. Navigate to /auth/signin\n2. Enter correct email\n3. Enter wrong password\n4. Click Sign In',
    expectedResult: 'Error: "Invalid email or password"',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-013',
    testCaseDescription: 'Sign in fails with non-existent email',
    preconditions: 'Email does not exist in database',
    testSteps: '1. Navigate to /auth/signin\n2. Enter non-existent email\n3. Enter any password\n4. Click Sign In',
    expectedResult: 'Error: "Invalid email or password" (generic message for security)',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-014',
    testCaseDescription: 'Rate limiting on sign-in endpoint',
    preconditions: 'Multiple sign-in attempts',
    testSteps: '1. Attempt 11 sign-ins within 15 minutes from same IP\n2. Observe response',
    expectedResult: '10 attempts succeed, 11th returns 429 Too Many Requests',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-015',
    testCaseDescription: 'Admin user redirected to admin panel',
    preconditions: 'Admin user with roles: ["admin", "user"]',
    testSteps: '1. Sign in as admin\n2. Observe redirect',
    expectedResult: 'Redirected to /admin',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-016',
    testCaseDescription: 'Student user redirected to dashboard',
    preconditions: 'Student user with roles: ["user"]',
    testSteps: '1. Sign in as student\n2. Observe redirect',
    expectedResult: 'Redirected to /dashboard',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-017',
    testCaseDescription: 'Sign in fails for suspended account',
    preconditions: 'User account status is "suspended"',
    testSteps: '1. Navigate to /auth/signin\n2. Enter suspended user email\n3. Enter password\n4. Click Sign In',
    expectedResult: 'Error: "Account suspended. Please contact support."',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Sign In',
    testCaseId: 'AUTH-018',
    testCaseDescription: 'Sign in fails for banned account',
    preconditions: 'User account status is "banned"',
    testSteps: '1. Navigate to /auth/signin\n2. Enter banned user email\n3. Enter password\n4. Click Sign In',
    expectedResult: 'Error: "Account banned. Please contact support."',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Password Reset',
    testCaseId: 'AUTH-019',
    testCaseDescription: 'User can request password reset',
    preconditions: 'User exists with verified email',
    testSteps: '1. Navigate to /auth/forgot-password\n2. Enter verified email\n3. Click Send Reset Link',
    expectedResult: 'Reset email sent, token generated (1h expiry), rate limit applied',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Password Reset',
    testCaseId: 'AUTH-020',
    testCaseDescription: 'User can reset password with valid token',
    preconditions: 'User requested password reset, received email',
    testSteps: '1. Click reset link in email\n2. Enter new password\n3. Confirm password\n4. Click Reset',
    expectedResult: 'Password updated, old sessions invalidated, user can sign in with new password',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Password Reset',
    testCaseId: 'AUTH-021',
    testCaseDescription: 'Password reset fails with expired token',
    preconditions: 'Reset token expired (>1 hour old)',
    testSteps: '1. Click expired reset link\n2. Enter new password\n3. Submit',
    expectedResult: 'Error: "Reset token expired. Please request a new one."',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Password Reset',
    testCaseId: 'AUTH-022',
    testCaseDescription: 'Password reset fails with invalid token',
    preconditions: 'Invalid or tampered token',
    testSteps: '1. Navigate to /auth/reset-password with invalid token\n2. Enter new password\n3. Submit',
    expectedResult: 'Error: "Invalid reset token"',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Password Reset',
    testCaseId: 'AUTH-023',
    testCaseDescription: 'Rate limiting on password reset',
    preconditions: 'Multiple reset requests',
    testSteps: '1. Request password reset 6 times within 1 hour\n2. Observe response',
    expectedResult: '5 requests succeed, 6th returns 429 Too Many Requests',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Session Management',
    testCaseId: 'AUTH-024',
    testCaseDescription: 'User can view active sessions',
    preconditions: 'User signed in',
    testSteps: '1. Navigate to /auth/sessions or profile page\n2. View sessions list',
    expectedResult: 'List shows all active sessions with device info, IP, last active time',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Session Management',
    testCaseId: 'AUTH-025',
    testCaseDescription: 'User can sign out from current session',
    preconditions: 'User signed in',
    testSteps: '1. Click Sign Out\n2. Confirm',
    expectedResult: 'Session invalidated, user redirected to home page',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Session Management',
    testCaseId: 'AUTH-026',
    testCaseDescription: 'User can sign out from all devices',
    preconditions: 'User signed in on multiple devices',
    testSteps: '1. Navigate to sessions page\n2. Click "Sign out all devices"',
    expectedResult: 'All sessions invalidated except current, user remains signed in',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Session Management',
    testCaseId: 'AUTH-027',
    testCaseDescription: 'Session expires after inactivity',
    preconditions: 'User signed in, session timeout configured',
    testSteps: '1. Sign in\n2. Wait for session timeout period\n3. Attempt to access protected route',
    expectedResult: 'Session expired, user redirected to sign in',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Role-Based Access Control',
    testCaseId: 'AUTH-028',
    testCaseDescription: 'Admin can access admin routes',
    preconditions: 'User signed in as admin',
    testSteps: '1. Navigate to /admin\n2. Access admin features',
    expectedResult: 'Admin panel accessible, all admin features visible',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Role-Based Access Control',
    testCaseId: 'AUTH-029',
    testCaseDescription: 'Student cannot access admin routes',
    preconditions: 'User signed in as student',
    testSteps: '1. Navigate to /admin\n2. Attempt to access admin features',
    expectedResult: 'Access denied, redirected to dashboard or 403 error',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Role-Based Access Control',
    testCaseId: 'AUTH-030',
    testCaseDescription: 'Unauthenticated user redirected to sign in',
    preconditions: 'User not signed in',
    testSteps: '1. Navigate to protected route (e.g., /dashboard, /admin)\n2. Observe behavior',
    expectedResult: 'Redirected to /auth/signin with return URL',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== EMAIL FUNCTIONALITY ==========
  {
    feature: 'Email Service',
    testCaseId: 'EMAIL-001',
    testCaseDescription: 'Verification email sent on registration',
    preconditions: 'User registers successfully',
    testSteps: '1. Register new user\n2. Check email inbox',
    expectedResult: 'Verification email received from noreply@edurepoai.xyz with valid link',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Service',
    testCaseId: 'EMAIL-002',
    testCaseDescription: 'Welcome email sent after verification',
    preconditions: 'User verifies email',
    testSteps: '1. Verify email\n2. Check email inbox',
    expectedResult: 'Welcome email received with app information',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Service',
    testCaseId: 'EMAIL-003',
    testCaseDescription: 'Password reset email sent',
    preconditions: 'User requests password reset',
    testSteps: '1. Request password reset\n2. Check email inbox',
    expectedResult: 'Password reset email received with valid reset link',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Service',
    testCaseId: 'EMAIL-004',
    testCaseDescription: 'Email templates render correctly',
    preconditions: 'Email sent',
    testSteps: '1. Open email in various clients (Gmail, Outlook, etc.)\n2. Check formatting',
    expectedResult: 'Email renders correctly with proper styling, links work, domain shows edurepoai.xyz',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Email Service',
    testCaseId: 'EMAIL-005',
    testCaseDescription: 'SendGrid API key validation',
    preconditions: 'Application running',
    testSteps: '1. Check environment variables\n2. Attempt to send email',
    expectedResult: 'API key validated, emails sent successfully via SendGrid',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== ADMIN FEATURES ==========
  {
    feature: 'Admin Dashboard',
    testCaseId: 'ADMIN-001',
    testCaseDescription: 'Admin can access dashboard',
    preconditions: 'User signed in as admin',
    testSteps: '1. Navigate to /admin\n2. View dashboard',
    expectedResult: 'Dashboard loads with statistics, charts, and admin features',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Users Management',
    testCaseId: 'ADMIN-002',
    testCaseDescription: 'Admin can view all users',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/users\n2. View users list',
    expectedResult: 'List of all users with email, role, status, registration date',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Users Management',
    testCaseId: 'ADMIN-003',
    testCaseDescription: 'Admin can update user status',
    preconditions: 'Admin viewing user details',
    testSteps: '1. Select user\n2. Change status (active/suspended/banned)\n3. Save',
    expectedResult: 'User status updated, changes reflected immediately',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Users Management',
    testCaseId: 'ADMIN-004',
    testCaseDescription: 'Admin can delete user',
    preconditions: 'Admin viewing user details',
    testSteps: '1. Select user\n2. Click Delete\n3. Confirm deletion',
    expectedResult: 'User deleted, removed from database, related data handled appropriately',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Institutions Management',
    testCaseId: 'ADMIN-005',
    testCaseDescription: 'Admin can view all institutions',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/institutions\n2. View institutions list',
    expectedResult: 'List of all institutions with details, searchable and filterable',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Institutions Management',
    testCaseId: 'ADMIN-006',
    testCaseDescription: 'Admin can create new institution',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/institutions\n2. Click Create\n3. Fill form\n4. Submit',
    expectedResult: 'Institution created, appears in list, data validated',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Institutions Management',
    testCaseId: 'ADMIN-007',
    testCaseDescription: 'Admin can update institution',
    preconditions: 'Admin viewing institution details',
    testSteps: '1. Select institution\n2. Edit details\n3. Save',
    expectedResult: 'Institution updated, changes reflected immediately',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
	  feature: 'Admin Institutions Management',
	  testCaseId: 'ADMIN-008',
	  testCaseDescription: 'Admin can delete institution',
	  preconditions: 'Admin viewing institution details',
	  testSteps: '1. Select institution\n2. Click Delete\n3. Confirm deletion',
	  expectedResult: 'Institution deleted, related programs handled appropriately',
	  priority: 'High',
	  status: 'Not Tested',
	  notes: '',
	  dateTested: '',
	  environment: 'Dev',
	  tester: ''
  },
  {
    feature: 'Admin Programs Management',
    testCaseId: 'ADMIN-009',
    testCaseDescription: 'Admin can view all programs',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/programs\n2. View programs list',
    expectedResult: 'List of all programs with details, searchable and filterable',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Programs Management',
    testCaseId: 'ADMIN-010',
    testCaseDescription: 'Admin can create new program',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/programs\n2. Click Create\n3. Fill form\n4. Submit',
    expectedResult: 'Program created, appears in list, linked to institution',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Programs Management',
    testCaseId: 'ADMIN-011',
    testCaseDescription: 'Admin can update program',
    preconditions: 'Admin viewing program details',
    testSteps: '1. Select program\n2. Edit details\n3. Save',
    expectedResult: 'Program updated, changes reflected immediately',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Programs Management',
    testCaseId: 'ADMIN-012',
    testCaseDescription: 'Admin can delete program',
    preconditions: 'Admin viewing program details',
    testSteps: '1. Select program\n2. Click Delete\n3. Confirm deletion',
    expectedResult: 'Program deleted, removed from database',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Bulk Operations',
    testCaseId: 'ADMIN-013',
    testCaseDescription: 'Admin can bulk import institutions',
    preconditions: 'Admin signed in, CSV file ready',
    testSteps: '1. Navigate to /admin/institutions/import\n2. Upload CSV\n3. Review mapping\n4. Import',
    expectedResult: 'Institutions imported, duplicates handled, validation errors reported',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Bulk Operations',
    testCaseId: 'ADMIN-014',
    testCaseDescription: 'Admin can bulk update programs',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/programs\n2. Select multiple programs\n3. Click Bulk Update\n4. Apply changes',
    expectedResult: 'Selected programs updated, success message shown',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Bulk Operations',
    testCaseId: 'ADMIN-015',
    testCaseDescription: 'Admin can bulk delete items',
    preconditions: 'Admin signed in',
    testSteps: '1. Select multiple items\n2. Click Bulk Delete\n3. Confirm',
    expectedResult: 'Selected items deleted, confirmation shown',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Data Quality',
    testCaseId: 'ADMIN-016',
    testCaseDescription: 'Admin can view data quality metrics',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/data-quality\n2. View metrics',
    expectedResult: 'Data quality dashboard shows coverage, completeness, freshness scores',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Analytics',
    testCaseId: 'ADMIN-017',
    testCaseDescription: 'Admin can view analytics',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/analytics\n2. View charts and statistics',
    expectedResult: 'Analytics dashboard shows user activity, popular searches, trends',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Admin Settings',
    testCaseId: 'ADMIN-018',
    testCaseDescription: 'Admin can update app settings',
    preconditions: 'Admin signed in',
    testSteps: '1. Navigate to /admin/settings\n2. Update settings\n3. Save',
    expectedResult: 'Settings saved, changes applied immediately',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== STUDENT FEATURES ==========
  {
    feature: 'Student Dashboard',
    testCaseId: 'STUDENT-001',
    testCaseDescription: 'Student can access dashboard',
    preconditions: 'Student signed in',
    testSteps: '1. Navigate to /dashboard\n2. View dashboard',
    expectedResult: 'Dashboard loads with personalized content, watchlist, recommendations',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Student Profile',
    testCaseId: 'STUDENT-002',
    testCaseDescription: 'Student can view profile',
    preconditions: 'Student signed in',
    testSteps: '1. Navigate to /profile\n2. View profile details',
    expectedResult: 'Profile shows email, registration date, preferences, saved data',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Student Profile',
    testCaseId: 'STUDENT-003',
    testCaseDescription: 'Student can update profile',
    preconditions: 'Student viewing profile',
    testSteps: '1. Edit profile fields\n2. Save changes',
    expectedResult: 'Profile updated, changes saved successfully',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Student Profile',
    testCaseId: 'STUDENT-004',
    testCaseDescription: 'Student can update JAMB score',
    preconditions: 'Student viewing profile',
    testSteps: '1. Navigate to profile\n2. Update JAMB score\n3. Save',
    expectedResult: 'JAMB score updated, recommendations recalculated',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Student Profile',
    testCaseId: 'STUDENT-005',
    testCaseDescription: 'Student can update O-level results',
    preconditions: 'Student viewing profile',
    testSteps: '1. Navigate to profile\n2. Update O-level grades\n3. Save',
    expectedResult: 'O-level results updated, eligibility calculations updated',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== INSTITUTION SEARCH & DISCOVERY ==========
  {
    feature: 'Institution Search',
    testCaseId: 'SEARCH-001',
    testCaseDescription: 'User can search institutions',
    preconditions: 'User on institutions page',
    testSteps: '1. Navigate to /institutions\n2. Enter search query\n3. Click Search',
    expectedResult: 'Relevant institutions displayed, results sorted by relevance',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Institution Search',
    testCaseId: 'SEARCH-002',
    testCaseDescription: 'User can filter institutions by type',
    preconditions: 'User on institutions page',
    testSteps: '1. Select institution type filter (University, Polytechnic, etc.)\n2. Apply filter',
    expectedResult: 'Only institutions matching type displayed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Institution Search',
    testCaseId: 'SEARCH-003',
    testCaseDescription: 'User can filter institutions by location',
    preconditions: 'User on institutions page',
    testSteps: '1. Select state filter\n2. Apply filter',
    expectedResult: 'Only institutions in selected state displayed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Institution Search',
    testCaseId: 'SEARCH-004',
    testCaseDescription: 'User can view institution details',
    preconditions: 'User viewing institutions list',
    testSteps: '1. Click on institution\n2. View details page',
    expectedResult: 'Institution details page shows all information, programs, statistics',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Program Search',
    testCaseId: 'SEARCH-005',
    testCaseDescription: 'User can search programs',
    preconditions: 'User on programs page',
    testSteps: '1. Navigate to /programs\n2. Enter search query\n3. Click Search',
    expectedResult: 'Relevant programs displayed with institution info',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Program Search',
    testCaseId: 'SEARCH-006',
    testCaseDescription: 'User can filter programs by institution',
    preconditions: 'User on programs page',
    testSteps: '1. Select institution filter\n2. Apply filter',
    expectedResult: 'Only programs from selected institution displayed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Program Search',
    testCaseId: 'SEARCH-007',
    testCaseDescription: 'User can view program details',
    preconditions: 'User viewing programs list',
    testSteps: '1. Click on program\n2. View details page',
    expectedResult: 'Program details page shows requirements, cutoffs, fees, accreditation',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== AI CHAT ==========
  {
    feature: 'AI Chat',
    testCaseId: 'AI-001',
    testCaseDescription: 'User can access AI chat',
    preconditions: 'User signed in',
    testSteps: '1. Navigate to /ai\n2. View chat interface',
    expectedResult: 'Chat interface loads, ready for input',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'AI Chat',
    testCaseId: 'AI-002',
    testCaseDescription: 'User can send message to AI',
    preconditions: 'User on AI chat page',
    testSteps: '1. Type message\n2. Click Send or press Enter',
    expectedResult: 'Message sent, AI response generated and displayed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'AI Chat',
    testCaseId: 'AI-003',
    testCaseDescription: 'AI provides relevant recommendations',
    preconditions: 'User asks about program recommendations',
    testSteps: '1. Ask: "What programs suit my JAMB score of 250?"\n2. Observe response',
    expectedResult: 'AI provides relevant program recommendations with explanations',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'AI Chat',
    testCaseId: 'AI-004',
    testCaseDescription: 'AI uses RAG for accurate information',
    preconditions: 'User asks institution-specific question',
    testSteps: '1. Ask: "What are the admission requirements for University of Lagos?"\n2. Observe response',
    expectedResult: 'AI retrieves accurate information from database using RAG',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'AI Chat',
    testCaseId: 'AI-005',
    testCaseDescription: 'Chat history persists',
    preconditions: 'User has previous chat history',
    testSteps: '1. Navigate to /ai\n2. View chat history',
    expectedResult: 'Previous conversations displayed, user can continue',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'AI Chat',
    testCaseId: 'AI-006',
    testCaseDescription: 'User can clear chat history',
    preconditions: 'User on AI chat page with history',
    testSteps: '1. Click Clear History\n2. Confirm',
    expectedResult: 'Chat history cleared, new conversation started',
    priority: 'Low',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== WATCHLIST ==========
  {
    feature: 'Watchlist',
    testCaseId: 'WATCH-001',
    testCaseDescription: 'User can add institution to watchlist',
    preconditions: 'User signed in, viewing institution',
    testSteps: '1. Navigate to institution page\n2. Click Add to Watchlist',
    expectedResult: 'Institution added to watchlist, notification preference saved',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Watchlist',
    testCaseId: 'WATCH-002',
    testCaseDescription: 'User can add program to watchlist',
    preconditions: 'User signed in, viewing program',
    testSteps: '1. Navigate to program page\n2. Click Add to Watchlist',
    expectedResult: 'Program added to watchlist, notification preference saved',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Watchlist',
    testCaseId: 'WATCH-003',
    testCaseDescription: 'User can view watchlist',
    preconditions: 'User signed in, has items in watchlist',
    testSteps: '1. Navigate to /watchlist\n2. View items',
    expectedResult: 'Watchlist displays all saved institutions and programs',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Watchlist',
    testCaseId: 'WATCH-004',
    testCaseDescription: 'User can remove item from watchlist',
    preconditions: 'User viewing watchlist',
    testSteps: '1. Select item\n2. Click Remove\n3. Confirm',
    expectedResult: 'Item removed from watchlist',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Watchlist',
    testCaseId: 'WATCH-005',
    testCaseDescription: 'User can bulk manage watchlist',
    preconditions: 'User viewing watchlist',
    testSteps: '1. Select multiple items\n2. Click Bulk Remove\n3. Confirm',
    expectedResult: 'Selected items removed from watchlist',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== REVIEWS & RATINGS ==========
  {
    feature: 'Reviews',
    testCaseId: 'REVIEW-001',
    testCaseDescription: 'User can view reviews for institution',
    preconditions: 'User viewing institution page',
    testSteps: '1. Navigate to institution page\n2. Scroll to reviews section',
    expectedResult: 'Reviews displayed with ratings, comments, helpful votes',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Reviews',
    testCaseId: 'REVIEW-002',
    testCaseDescription: 'User can submit review',
    preconditions: 'User signed in, viewing institution',
    testSteps: '1. Navigate to institution page\n2. Click Write Review\n3. Fill form\n4. Submit',
    expectedResult: 'Review submitted, appears in reviews list',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Reviews',
    testCaseId: 'REVIEW-003',
    testCaseDescription: 'User can rate helpfulness of review',
    preconditions: 'User viewing reviews',
    testSteps: '1. Click Helpful on review\n2. Observe update',
    expectedResult: 'Helpful count incremented, user cannot vote twice',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Reviews',
    testCaseId: 'REVIEW-004',
    testCaseDescription: 'User can report inappropriate review',
    preconditions: 'User viewing reviews',
    testSteps: '1. Click Report on review\n2. Select reason\n3. Submit',
    expectedResult: 'Review reported, admin notified',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== CALCULATORS ==========
  {
    feature: 'Eligibility Calculator',
    testCaseId: 'CALC-001',
    testCaseDescription: 'User can calculate admission eligibility',
    preconditions: 'User signed in with JAMB and O-level scores',
    testSteps: '1. Navigate to calculator\n2. Select program\n3. View eligibility',
    expectedResult: 'Eligibility percentage calculated, admission probability shown',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Eligibility Calculator',
    testCaseId: 'CALC-002',
    testCaseDescription: 'Calculator uses historical cutoff data',
    preconditions: 'Program has historical cutoff data',
    testSteps: '1. Calculate eligibility for program with cutoffs\n2. View result',
    expectedResult: 'Calculation based on historical data, confidence interval shown',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Fee Calculator',
    testCaseId: 'CALC-003',
    testCaseDescription: 'User can calculate program fees',
    preconditions: 'User viewing program with fee data',
    testSteps: '1. Navigate to program page\n2. View fee calculator\n3. Calculate total fees',
    expectedResult: 'Total fees calculated including tuition, accommodation, etc.',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== NOTIFICATIONS ==========
  {
    feature: 'Notifications',
    testCaseId: 'NOTIF-001',
    testCaseDescription: 'User receives notifications',
    preconditions: 'User signed in, has watchlist items',
    testSteps: '1. Wait for notification trigger\n2. Check notifications',
    expectedResult: 'Notification appears in notification center',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Notifications',
    testCaseId: 'NOTIF-002',
    testCaseDescription: 'User can view all notifications',
    preconditions: 'User signed in',
    testSteps: '1. Navigate to notifications page\n2. View list',
    expectedResult: 'All notifications displayed, unread marked',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Notifications',
    testCaseId: 'NOTIF-003',
    testCaseDescription: 'User can mark notification as read',
    preconditions: 'User viewing notifications',
    testSteps: '1. Click on notification\n2. Observe status',
    expectedResult: 'Notification marked as read, unread count updated',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Notifications',
    testCaseId: 'NOTIF-004',
    testCaseDescription: 'User can manage notification preferences',
    preconditions: 'User signed in',
    testSteps: '1. Navigate to notification settings\n2. Update preferences\n3. Save',
    expectedResult: 'Preferences saved, notifications sent according to settings',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== UI/UX ==========
  {
    feature: 'Responsive Design',
    testCaseId: 'UI-001',
    testCaseDescription: 'App is responsive on mobile devices',
    preconditions: 'Access app on mobile device or resize browser',
    testSteps: '1. Open app on mobile (375px width)\n2. Navigate through pages\n3. Test interactions',
    expectedResult: 'All pages render correctly, navigation works, forms usable',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Responsive Design',
    testCaseId: 'UI-002',
    testCaseDescription: 'App is responsive on tablet devices',
    preconditions: 'Access app on tablet or resize browser',
    testSteps: '1. Open app on tablet (768px width)\n2. Navigate through pages\n3. Test interactions',
    expectedResult: 'All pages render correctly, layout optimized for tablet',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Responsive Design',
    testCaseId: 'UI-003',
    testCaseDescription: 'App is responsive on desktop',
    preconditions: 'Access app on desktop',
    testSteps: '1. Open app on desktop (1920px width)\n2. Navigate through pages\n3. Test interactions',
    expectedResult: 'All pages render correctly, full layout visible',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Navigation',
    testCaseId: 'UI-004',
    testCaseDescription: 'Navbar displays correctly',
    preconditions: 'User on any page',
    testSteps: '1. View navbar\n2. Check links and dropdowns',
    expectedResult: 'Navbar shows correct links, dropdowns work, responsive menu functions',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Navigation',
    testCaseId: 'UI-005',
    testCaseDescription: 'Footer displays correctly',
    preconditions: 'User on any page',
    testSteps: '1. Scroll to footer\n2. Check links and content',
    expectedResult: 'Footer shows correct information, links work, domain shows edurepoai.xyz',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Loading States',
    testCaseId: 'UI-006',
    testCaseDescription: 'Loading indicators display during async operations',
    preconditions: 'User performs action requiring API call',
    testSteps: '1. Trigger action (search, submit form, etc.)\n2. Observe loading state',
    expectedResult: 'Loading indicator shown, user feedback provided',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Error Handling',
    testCaseId: 'UI-007',
    testCaseDescription: 'Error messages display correctly',
    preconditions: 'Error occurs (network, validation, etc.)',
    testSteps: '1. Trigger error condition\n2. Observe error message',
    expectedResult: 'Clear, user-friendly error message displayed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Accessibility',
    testCaseId: 'UI-008',
    testCaseDescription: 'App is accessible with keyboard navigation',
    preconditions: 'User navigates with keyboard only',
    testSteps: '1. Use Tab to navigate\n2. Use Enter/Space to activate\n3. Test all interactive elements',
    expectedResult: 'All elements accessible, focus indicators visible, logical tab order',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Accessibility',
    testCaseId: 'UI-009',
    testCaseDescription: 'App has proper ARIA labels',
    preconditions: 'Screen reader enabled',
    testSteps: '1. Navigate with screen reader\n2. Check announcements',
    expectedResult: 'All interactive elements have proper ARIA labels, announcements clear',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== PERFORMANCE ==========
  {
    feature: 'Performance',
    testCaseId: 'PERF-001',
    testCaseDescription: 'Page load times are acceptable',
    preconditions: 'Fresh page load',
    testSteps: '1. Measure page load time\n2. Check Core Web Vitals',
    expectedResult: 'Page loads in < 3 seconds, LCP < 2.5s, FID < 100ms, CLS < 0.1',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Performance',
    testCaseId: 'PERF-002',
    testCaseDescription: 'Search results load quickly',
    preconditions: 'User performs search',
    testSteps: '1. Enter search query\n2. Measure response time',
    expectedResult: 'Results displayed in < 1 second',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Performance',
    testCaseId: 'PERF-003',
    testCaseDescription: 'AI chat responses are timely',
    preconditions: 'User sends message to AI',
    testSteps: '1. Send message\n2. Measure response time',
    expectedResult: 'AI response received in < 5 seconds',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Performance',
    testCaseId: 'PERF-004',
    testCaseDescription: 'Database queries are optimized',
    preconditions: 'Admin viewing large dataset',
    testSteps: '1. Load users/institutions list\n2. Measure query time',
    expectedResult: 'Queries complete in < 500ms, pagination works',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== SECURITY ==========
  {
    feature: 'Security',
    testCaseId: 'SEC-001',
    testCaseDescription: 'SQL injection prevention',
    preconditions: 'User attempts SQL injection',
    testSteps: '1. Enter SQL injection payload in search/forms\n2. Submit',
    expectedResult: 'Input sanitized, no SQL executed, error handled gracefully',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Security',
    testCaseId: 'SEC-002',
    testCaseDescription: 'XSS prevention',
    preconditions: 'User attempts XSS attack',
    testSteps: '1. Enter XSS payload in forms\n2. Submit',
    expectedResult: 'Input sanitized, script tags escaped, no XSS executed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Security',
    testCaseId: 'SEC-003',
    testCaseDescription: 'CSRF protection',
    preconditions: 'External site attempts CSRF',
    testSteps: '1. Create external form targeting API\n2. Submit from external site',
    expectedResult: 'CSRF token validated, request rejected if invalid',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Security',
    testCaseId: 'SEC-004',
    testCaseDescription: 'Rate limiting prevents abuse',
    preconditions: 'Multiple rapid requests',
    testSteps: '1. Send rapid requests to rate-limited endpoint\n2. Observe response',
    expectedResult: 'Rate limit enforced, 429 returned after limit, IP tracked',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Security',
    testCaseId: 'SEC-005',
    testCaseDescription: 'Sensitive data encrypted',
    preconditions: 'Data stored in database',
    testSteps: '1. Check database for sensitive fields\n2. Verify encryption',
    expectedResult: 'Passwords hashed (bcrypt), sensitive data encrypted at rest',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Security',
    testCaseId: 'SEC-006',
    testCaseDescription: 'HTTPS enforced in production',
    preconditions: 'Application in production',
    testSteps: '1. Attempt HTTP connection\n2. Observe redirect',
    expectedResult: 'HTTP requests redirected to HTTPS',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Production'
  },
  {
    feature: 'Security',
    testCaseId: 'SEC-007',
    testCaseDescription: 'Security headers present',
    preconditions: 'Application running',
    testSteps: '1. Check HTTP response headers\n2. Verify security headers',
    expectedResult: 'CSP, X-Frame-Options, X-Content-Type-Options, HSTS headers present',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== API ENDPOINTS ==========
  {
    feature: 'API Endpoints',
    testCaseId: 'API-001',
    testCaseDescription: 'API returns correct status codes',
    preconditions: 'API endpoint called',
    testSteps: '1. Call API endpoint\n2. Check status code',
    expectedResult: '200 for success, 400 for bad request, 401 for unauthorized, 404 for not found, 500 for server error',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'API Endpoints',
    testCaseId: 'API-002',
    testCaseDescription: 'API validates request data',
    preconditions: 'Invalid data sent to API',
    testSteps: '1. Send invalid data\n2. Observe response',
    expectedResult: '400 Bad Request with validation error details',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'API Endpoints',
    testCaseId: 'API-003',
    testCaseDescription: 'API requires authentication for protected routes',
    preconditions: 'User not authenticated',
    testSteps: '1. Call protected API endpoint\n2. Observe response',
    expectedResult: '401 Unauthorized, authentication required',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'API Endpoints',
    testCaseId: 'API-004',
    testCaseDescription: 'API pagination works correctly',
    preconditions: 'Large dataset available',
    testSteps: '1. Call API with pagination params\n2. Verify results',
    expectedResult: 'Results paginated, page info included, next/prev links work',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'API Endpoints',
    testCaseId: 'API-005',
    testCaseDescription: 'API error handling is consistent',
    preconditions: 'Error occurs in API',
    testSteps: '1. Trigger error condition\n2. Check error response',
    expectedResult: 'Consistent error format, appropriate status code, helpful error message',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== DATA QUALITY ==========
  {
    feature: 'Data Quality',
    testCaseId: 'DATA-001',
    testCaseDescription: 'Institution data is complete',
    preconditions: 'Institution record exists',
    testSteps: '1. View institution details\n2. Check required fields',
    expectedResult: 'All required fields populated, data quality score displayed',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Data Quality',
    testCaseId: 'DATA-002',
    testCaseDescription: 'Program data is complete',
    preconditions: 'Program record exists',
    testSteps: '1. View program details\n2. Check required fields',
    expectedResult: 'All required fields populated, accreditation status shown',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Data Quality',
    testCaseId: 'DATA-003',
    testCaseDescription: 'Data freshness is tracked',
    preconditions: 'Data record exists',
    testSteps: '1. View data record\n2. Check last updated timestamp',
    expectedResult: 'Last updated date shown, freshness indicator displayed',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Data Quality',
    testCaseId: 'DATA-004',
    testCaseDescription: 'Data quality scores are accurate',
    preconditions: 'Data with quality score',
    testSteps: '1. View data quality metrics\n2. Verify score calculation',
    expectedResult: 'Quality score reflects completeness, accuracy, freshness',
    priority: 'Medium',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },

  // ========== INTEGRATION ==========
  {
    feature: 'Integration',
    testCaseId: 'INT-001',
    testCaseDescription: 'SendGrid email integration works',
    preconditions: 'Email sending required',
    testSteps: '1. Trigger email send (verification, reset, etc.)\n2. Check email delivery',
    expectedResult: 'Email sent successfully via SendGrid, received by recipient',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Integration',
    testCaseId: 'INT-002',
    testCaseDescription: 'Database connection is stable',
    preconditions: 'Application running',
    testSteps: '1. Perform database operations\n2. Monitor connection',
    expectedResult: 'Database operations succeed, connection pool managed correctly',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Integration',
    testCaseId: 'INT-003',
    testCaseDescription: 'Redis/KV store works for rate limiting',
    preconditions: 'Rate limiting enabled',
    testSteps: '1. Trigger rate-limited endpoint\n2. Verify rate limit tracking',
    expectedResult: 'Rate limits tracked in Redis/KV, limits enforced correctly',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  },
  {
    feature: 'Integration',
    testCaseId: 'INT-004',
    testCaseDescription: 'Prisma migrations apply correctly',
    preconditions: 'Schema changes made',
    testSteps: '1. Run migration\n2. Verify database schema',
    expectedResult: 'Migration applied, schema updated, data preserved',
    priority: 'High',
    status: 'Not Tested',
    notes: '',
    tester: '',
    dateTested: '',
    environment: 'Dev'
  }
];

function generateQASheet() {
  // Convert test cases to worksheet format
  const worksheetData = testCases.map((tc, index) => ({
    'No.': index + 1,
    'Feature/Module': tc.feature,
    'Test Case ID': tc.testCaseId,
    'Test Case Description': tc.testCaseDescription,
    'Preconditions': tc.preconditions,
    'Test Steps': tc.testSteps,
    'Expected Result': tc.expectedResult,
    'Priority': tc.priority,
    'Status': tc.status,
    'Notes/Comments': tc.notes,
    'Tester': tc.tester,
    'Date Tested': tc.dateTested,
    'Environment': tc.environment
  }));

  // Create workbook and worksheet
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.json_to_sheet(worksheetData);

  // Set column widths
  const columnWidths = [
    { wch: 5 },   // No.
    { wch: 25 },  // Feature/Module
    { wch: 15 },  // Test Case ID
    { wch: 50 },  // Test Case Description
    { wch: 40 },  // Preconditions
    { wch: 60 },  // Test Steps
    { wch: 50 },  // Expected Result
    { wch: 10 },  // Priority
    { wch: 12 },  // Status
    { wch: 30 },  // Notes/Comments
    { wch: 15 },  // Tester
    { wch: 15 },  // Date Tested
    { wch: 12 }   // Environment
  ];
  worksheet['!cols'] = columnWidths;

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, 'QA Test Cases');

  // Create summary sheet
  const summaryData = [
    { 'Feature': 'Total Test Cases', 'Count': testCases.length },
    { 'Feature': 'High Priority', 'Count': testCases.filter(tc => tc.priority === 'High').length },
    { 'Feature': 'Medium Priority', 'Count': testCases.filter(tc => tc.priority === 'Medium').length },
    { 'Feature': 'Low Priority', 'Count': testCases.filter(tc => tc.priority === 'Low').length },
    { 'Feature': 'Not Tested', 'Count': testCases.filter(tc => tc.status === 'Not Tested').length },
    { 'Feature': 'Passed', 'Count': testCases.filter(tc => tc.status === 'Pass').length },
    { 'Feature': 'Failed', 'Count': testCases.filter(tc => tc.status === 'Fail').length },
    { 'Feature': 'Blocked', 'Count': testCases.filter(tc => tc.status === 'Blocked').length }
  ];

  const summarySheet = XLSX.utils.json_to_sheet(summaryData);
  summarySheet['!cols'] = [{ wch: 25 }, { wch: 10 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Write file
  const filePath = 'qa_edurepo.xlsx';
  XLSX.writeFile(workbook, filePath);
  console.log(`✅ QA test sheet created: ${filePath}`);
  console.log(`📊 Total test cases: ${testCases.length}`);
  console.log(`   - High Priority: ${testCases.filter(tc => tc.priority === 'High').length}`);
  console.log(`   - Medium Priority: ${testCases.filter(tc => tc.priority === 'Medium').length}`);
  console.log(`   - Low Priority: ${testCases.filter(tc => tc.priority === 'Low').length}`);
}

generateQASheet();

